package:
  name:    '{{ name }}'
  version: '{{ version }}'


build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path:
    ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
