package:
  name:    '{{ name }}'
  version: '{{ version }}'


build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path:
    ../

requirements:
  build:
    - python {{ python }}
    - setuptools
    - six 1.*
    - deprecation 1.*
    - numpy 1.*
    - scipy >=0.18,<1
    - nibabel 2.*
    - sphinx 1.6.*
    - sphinx_rtd_theme 0.*
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
    - pytest-runner >=2.*,<=3.*

  run:
    - python
    - six 1.*
    - deprecation 1.*
    - numpy 1.*
    - scipy >=0.18,<1
    - nibabel 2.*

  run_constrained:
    - indexed_gzip >=0.6.1,<1
    - wxpython >=3.0.2.0,<4.1
    - trimesh 2.*
    - rtree 0.8
